/*
 * @Author: wangjiaxin@leedarson.com
 * @Date: 2019-09-03 11:13:30
 * Copyright © Leedarson. All rights reserved.
 */

export const THEME_COLORS = [
  'transparent',
  'background',
  'primary',
  'secondary',
  'info',
  'success',
  'error',
  'warn',
  'surface',
  'neuter50',
  'neuter100',
  'neuter200',
  'neuter300',
  'neuter400',
  'neuter500',
  'neuter600',
  'neuter700',
  'neuter800',
  'neuter900',
];

export const ICONS = [
  'question',
  'temporary',
  'alarm',
  'favorite',
  'favorite-selected',
  'group',
  'group-selected',
  'arrow-right',
  'arrow-left',
  'timer',
  'countdown',
  'battery',
  'success',
  'fail',
  'back',
  'bright',
  'bright-less',
  'automation',
  'clear',
  'remove',
  'edit',
  'email',
  'eye-close',
  'eye-open',
  'home',
  'integration',
  'location',
  'menu',
  'more',
  'password',
  'plus',
  'record',
  'scene',
  'search',
  'security',
  'selected',
  'setting',
  'sort',
  'triangle',
  'user',
  'verification',
  'wifi',
  'trash',
  'cleaner-reset',
  'speed',
  'speed-low',
  'speed-middle',
  'speed-strong',
  'curtain-close',
  'curtain-open',
  'pause',
  'play',
  'power',
  'arrow-down',
  'arrow-up',
  'lock',
  'phone',
  'scan',
];

export const PROP_TYPES_LOADING = ['bars', 'spin', 'bubbles', 'spokes'];

export const EMPTY_FUNCTION = () => {};
