import * as validation from './_util/validation';
import './styles/index.scss';
// export Select from './select';
// export Modal from './modal';
import button from './button';
// export Switch from './switch';
// export Collapse from './collapse';
// export Tabs from './tabs';
// export Drawer from './drawer';
import icon from './icon';
// export Toast from './toast';
// export CoolPanel from './coolpanel';
// export cooStore from './cooStore';
// export Lazyimg from './lazyimg';
// export Placebo from './placebo';
// export Dropdown from './dropdown';
// export Input from './input';
// export Form from './form';
// export Uploader from './uploader';
// export Editor from './editor';
// export NoneData from './noneData';
// export Loading from './loading';
import alert from './alert';

export const Button = button;
export const Icon = icon;
export const Alert = alert;
export const Validation = validation;
